// Text for the cut scenes
export const PartyText = {
  scene1: [
    { id: 1,  label: "As soon as you step into the house..." },
    { id: 2,  label: "you hear music blasting in the living room." },
    { id: 3,  label: "Chuckling at the sight of someone attempting a keg stand..." },
    { id: 4,  label: "you look around the room for your friend." },
    { id: 5,  label: "Through all the music and indistinct conversations..." },
    { id: 6,  label: "you hear your friend." },
    { id: 7,  label: "\"HEYYY! It\'s you!!!\"" },
    { id: 8,  label: "\"What\'s up, what\'s up? You\'re late to the party.\"" },
    { id: 9,  label: "Your friend gives you a hug and you get a large whiff of alcohol." },
    { id: 10, label: "You laugh." },
    { id: 11, label: "Before you can ask about how much alcohol they\'ve drank..." },
    { id: 12, label: "Your friend announces to the room..." },
    { id: 13, label: "\"MORE SHOTS FOR EVERYONE\" and drags you to the kitchen." },
    { id: 14, label: "Your friend pours a hefty amount of everclear into a red solo cup..." },
    { id: 15, label: "and comes back to you with a mischievous smile." },
    { id: 15, label: "\"Take it.\"" },
  ],
  scene2: [
    { id: 16, label: "When you look up after regaining balance..." },
    { id: 17, label: "You realize that you\'re in a dark room..." },
    { id: 18, label: "full..." },
    { id: 19, label: "full...\nof mannequins."},
    { id: 20, label: "You notice movement behind the mannequins." },
    { id: 21, label: "You see it." },
    { id: 22, label: "The dark figure." },
  ],
  scene2DrinkIntro: [
    { id: 23, label: "As you finish inhaling an absurd amount of ever clear..." },
    { id: 24, label: "your head starts to spin." },
  ],
  scene2RefuseIntro: [
    { id: 25, label: "As you push away the drink..." },
    { id: 26, label: "your head starts to spin."},
  ],
};

export const EndingText = {
  badEnding1: [
    { id: 1, label: "You get in the car. The doors were open."},
    { id: 2, label: "As if by instinct,"},
    { id: 3, label: "As if by instinct,\nyou reached inside your pockets"},
    { id: 4, label: "As if by instinct,\nyou reached inside your pockets\nand pulled out a key."},
    { id: 5, label: "\"Was that always there?\""},
    { id: 6, label: "Doesn\'t matter."},
    { id: 7, label: "You put the keys in the ignition"},
    { id: 8, label: "You put the keys in the ignition\nand started the car."},
    { id: 9, label: "As the engine starts..."},
    { id: 10, label: "you notice that the car reeks of booze."},
    { id: 11, label: "You speed away..."},
    { id: 12, label: "Escaping whatever you had just experienced."},
    { id: 13, label: "You're relieved. It's finally over."},
    { id: 14, label: "You made it out. But from whe-"},
    { id: 15, label: "\"AHHHHHHHHHHHHH\""},
    { id: 16, label: "Your thoughts are interrupted by a scream from behind."},
    { id: 17, label: "You look,"},
    { id: 18, label: "You look,\nbut there's no one there."},
    { id: 19, label: "*CRASH*"},
    { id: 20, label: "..."},
    { id: 21, label: "Pain"},
    { id: 22, label: "..."},
    { id: 23, label: "Losing..."},
    { id: 24, label: "Losing...\nConsciousness..."},
  ],
  badEnding2: [
    { id: 25, label: "\"What was that?\" you think."},
    { id: 26, label: "You know that you're missing something..."},
    { id: 27, label: "but the pain from the fall"},
    { id: 28, label: "but the pain from the fall\nfocuses your mind"},
    { id: 29, label: "but the pain from the fall\nfocuses your mind\non a singular goal:"},
    { id: 30, label: "but the pain from the fall\nfocuses your mind\non a singular goal:\nrun"},
    { id: 31, label: "You crawl away, as far as you can."},
    { id: 32, label: "You feel lightheaded..."},
    { id: 33, label: "..."},
    { id: 34, label: "Losing..."},
    { id: 35, label: "Losing...\nConsciousness..."},
  ],
  goodEnding: [
    { id: 36, label: "It's dark outside..."},
    { id: 37, label: "but you see a light in the distance."},
    { id: 38, label: "You run..."},
    { id: 39, label: "You run until you feel"},
    { id: 40, label: "You run until you feel\nlike your lungs are on fire."},
    { id: 41, label: "With the pain comes your memories."},
    { id: 42, label: "And with the memories come emotions."},
    { id: 43, label: "Regret."},
    { id: 44, label: "Regret.\nShame."},
    { id: 45, label: "Regret.\nShame.\nGuilt."},
    { id: 46, label: "Regret.\nShame.\nGuilt.\nRelief."},
    { id: 47, label: "Tears run down your cheeks."},
    { id: 48, label: "You want to cry, but you don't stop running."},
    { id: 49, label: "The light is close now."},
    { id: 50, label: "And it's time"},
    { id: 51, label: "And it's time\nto move on."},
  ],
};